version: '3'
services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - contato-network
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    networks:
      - contato-network
  app_contato:
    build:
      context: ./api_contato
    ports:
      - 3000:3000
    links:
      - mysql
      - postgresql
    networks:
      - contato-network
    depends_on:
      - postgresql
      - mysql    
networks:
  contato-network:
    driver: bridge
