version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - webnet
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    networks:
      - webnet
  app:
    container_name: app
    build:
      context: ./teste/.
    ports:
      - 3000:3000
    links:
      - mysql
      - postgresql
    networks:
      - webnet
    depends_on:
      - postgresql
      - mysql    
networks:
    webnet:
        driver: bridge
